# ============================================================
# AURA - SALES DATA ANALYSIS
# DASHBOARD APPLICATION
# ============================================================

import os
import sys
from io import BytesIO


# ------------------------------------------------------------
# ADD AURA PROJECT ROOT TO PYTHON PATH
# ------------------------------------------------------------
# app.py is inside Dashboard/
# Engines/ is outside Dashboard/
# So we add the main AURA folder to Python's search path.
# ------------------------------------------------------------

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)


# ------------------------------------------------------------
# FLASK IMPORTS
# ------------------------------------------------------------

from flask import Flask, render_template, send_file


# ------------------------------------------------------------
# PDF IMPORTS
# ------------------------------------------------------------

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader


# ------------------------------------------------------------
# MATPLOTLIB
# ------------------------------------------------------------

import matplotlib.pyplot as plt


# ------------------------------------------------------------
# EXISTING AURA BACKEND MODULES
# ------------------------------------------------------------

from Engines.Data.load_dataset import load_dataset

from Engines.Visualization.bar_chart import bar_chart
from Engines.Visualization.line_chart import line_chart
from Engines.Visualization.pie_chart import pie_chart
from Engines.Visualization.scatter_plot import scatter_plot
from Engines.Visualization.histogram import histogram
from Engines.Visualization.box_plot import box_plot
from Engines.Visualization.heatmap import heatmap


# ============================================================
# CREATE FLASK APPLICATION
# ============================================================

app = Flask(__name__)


# ============================================================
# DASHBOARD
# ============================================================

@app.route("/")
def dashboard():

    data = {
        "revenue": "₹12,45,000",
        "orders": "2,458",
        "customers": "1,856",
        "avg_order": "₹998"
    }

    return render_template(
        "dashboard.html",
        data=data
    )


# ============================================================
# OTHER PAGES
# ============================================================

@app.route("/sales")
def sales():
    return render_template("sales.html")


@app.route("/products")
def products():
    return render_template("products.html")


@app.route("/categories")
def categories():
    return render_template("categories.html")


@app.route("/customers")
def customers():
    return render_template("customers.html")


@app.route("/orders")
def orders():
    return render_template("orders.html")


@app.route("/returns")
def returns():
    return render_template("returns.html")


@app.route("/inventory")
def inventory():
    return render_template("inventory.html")


@app.route("/marketing")
def marketing():
    return render_template("marketing.html")


@app.route("/reports")
def reports():
    return render_template("reports.html")


@app.route("/alerts")
def alerts():
    return render_template("alerts.html")


@app.route("/settings")
def settings():
    return render_template("settings.html")


@app.route("/help")
def help_page():
    return render_template("help.html")


# ============================================================
# CAPTURE EXISTING AURA GRAPH
# ============================================================
#
# Your existing graph functions use plt.show().
# For PDF export we don't want separate graph windows.
#
# This function temporarily disables plt.show(),
# runs the EXISTING visualization function,
# captures the graph, and returns it as an image.
#
# No graph logic is recreated here.
# ============================================================

def capture_graph(graph_function, dataset):

    # Store original show function
    original_show = plt.show

    # Prevent graph popup window
    plt.show = lambda: None

    # Clear previous figures
    plt.close("all")

    try:

        # Run existing AURA visualization
        result = graph_function(dataset)

        if result is None:
            return None

        # Get graph generated by existing function
        figure = plt.gcf()

        # Store graph in memory
        image = BytesIO()

        figure.savefig(
            image,
            format="png",
            dpi=160,
            bbox_inches="tight"
        )

        image.seek(0)

        return image

    finally:

        plt.close("all")

        # Restore plt.show()
        plt.show = original_show


# ============================================================
# ADD GRAPH PAGE TO PDF
# ============================================================

def add_graph_page(c, width, height, title, image):

    # Page title
    c.setFillColor(
        colors.HexColor("#6334F4")
    )

    c.setFont(
        "Helvetica-Bold",
        19
    )

    c.drawString(
        50,
        height - 55,
        title
    )


    # Divider line
    c.setStrokeColor(
        colors.HexColor("#6334F4")
    )

    c.setLineWidth(2)

    c.line(
        50,
        height - 72,
        width - 50,
        height - 72
    )


    # Insert graph
    if image is not None:

        c.drawImage(
            ImageReader(image),
            45,
            170,
            width=500,
            height=540,
            preserveAspectRatio=True
        )

    else:

        c.setFillColor(colors.red)

        c.setFont(
            "Helvetica",
            12
        )

        c.drawString(
            50,
            height - 130,
            "Unable to generate this visualization."
        )


    # Footer
    c.setFillColor(
        colors.grey
    )

    c.setFont(
        "Helvetica-Oblique",
        9
    )

    c.drawString(
        50,
        35,
        "Generated using AURA Visualization Engine"
    )


# ============================================================
# EXPORT COMPLETE PDF REPORT
# ============================================================

@app.route("/export-report")
def export_report():

    # --------------------------------------------------------
    # IMPORTANT
    # --------------------------------------------------------
    # load_dataset.py uses this relative path:
    #
    # Dataset/RAW/AURA.csv
    #
    # Therefore we temporarily make the AURA root folder
    # the working directory before loading the dataset.
    # --------------------------------------------------------

    old_directory = os.getcwd()

    os.chdir(BASE_DIR)

    try:

        # Load actual AURA dataset
        dataset = load_dataset()

    finally:

        # Restore previous working directory
        os.chdir(old_directory)


    if dataset is None:

        return (
            "Unable to load Dataset/RAW/AURA.csv. "
            "Please check the dataset path."
        )


    # --------------------------------------------------------
    # GENERATE GRAPHS USING EXISTING VISUALIZATION ENGINE
    # --------------------------------------------------------

    bar_image = capture_graph(
        bar_chart,
        dataset
    )

    line_image = capture_graph(
        line_chart,
        dataset
    )

    pie_image = capture_graph(
        pie_chart,
        dataset
    )

    scatter_image = capture_graph(
        scatter_plot,
        dataset
    )

    histogram_image = capture_graph(
        histogram,
        dataset
    )

    box_image = capture_graph(
        box_plot,
        dataset
    )

    heatmap_image = capture_graph(
        heatmap,
        dataset
    )


    # --------------------------------------------------------
    # CREATE PDF
    # --------------------------------------------------------

    pdf = BytesIO()

    c = canvas.Canvas(
        pdf,
        pagesize=A4
    )

    width, height = A4


    # ========================================================
    # PAGE 1 - REPORT COVER / SUMMARY
    # ========================================================

    c.setFillColor(
        colors.HexColor("#6334F4")
    )

    c.setFont(
        "Helvetica-Bold",
        26
    )

    c.drawString(
        50,
        height - 60,
        "AURA"
    )


    c.setFillColor(
        colors.black
    )

    c.setFont(
        "Helvetica",
        13
    )

    c.drawString(
        50,
        height - 85,
        "Sales Data Analysis Report"
    )


    # Divider
    c.setStrokeColor(
        colors.HexColor("#6334F4")
    )

    c.setLineWidth(2)

    c.line(
        50,
        height - 100,
        width - 50,
        height - 100
    )


    # Dataset details
    c.setFont(
        "Helvetica-Bold",
        16
    )

    c.drawString(
        50,
        height - 145,
        "Dataset Summary"
    )


    c.setFont(
        "Helvetica",
        12
    )

    c.drawString(
        60,
        height - 180,
        f"Total Rows: {dataset.shape[0]}"
    )

    c.drawString(
        60,
        height - 205,
        f"Total Columns: {dataset.shape[1]}"
    )


    # Dataset column names
    c.setFont(
        "Helvetica-Bold",
        16
    )

    c.drawString(
        50,
        height - 250,
        "Dataset Columns"
    )


    c.setFont(
        "Helvetica",
        10
    )

    y = height - 280


    for column in dataset.columns:

        c.drawString(
            60,
            y,
            str(column)
        )

        y -= 18

        # Prevent writing outside page
        if y < 90:
            break


    # Footer
    c.setFillColor(
        colors.grey
    )

    c.setFont(
        "Helvetica-Oblique",
        9
    )

    c.drawString(
        50,
        35,
        "AURA - Sales Data Analysis"
    )


    # ========================================================
    # PAGE 2 - BAR CHART
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Product Sales",
        bar_image
    )


    # ========================================================
    # PAGE 3 - LINE CHART
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Sales Trend",
        line_image
    )


    # ========================================================
    # PAGE 4 - PIE CHART
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Sales Distribution by Category",
        pie_image
    )


    # ========================================================
    # PAGE 5 - SCATTER PLOT
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Price vs Sales",
        scatter_image
    )


    # ========================================================
    # PAGE 6 - HISTOGRAM
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Price Distribution",
        histogram_image
    )


    # ========================================================
    # PAGE 7 - BOX PLOT
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Price Distribution and Outliers",
        box_image
    )


    # ========================================================
    # PAGE 8 - HEATMAP
    # ========================================================

    c.showPage()

    add_graph_page(
        c,
        width,
        height,
        "Correlation Heatmap",
        heatmap_image
    )


    # --------------------------------------------------------
    # FINISH PDF
    # --------------------------------------------------------

    c.save()

    pdf.seek(0)


    return send_file(
        pdf,
        as_attachment=True,
        download_name="AURA_Complete_Analytics_Report.pdf",
        mimetype="application/pdf"
    )


# ============================================================
# RUN APPLICATION
# ============================================================

if __name__ == "__main__":

    app.run(
        debug=True
    )